apiVersion: v1
kind: Secret
metadata:
  name: sbms-secrets
  namespace: sbms
type: Opaque
data:
  DB_HOST: cG9z...
  DB_NAME: c2Jt...
  DB_USERNAME: c2...
  DB_PASSWORD: c3VwM3....
  REDIS_HOST: cmVka...
  MQ_USERNAME: YWR...
  MQ_PASSWORD: cjR...
  MQ_HOST: cmFi...
  MAIL_HOST: bGl2Z....
  MAIL_PORT: MjU...
  MAIL_USERNAME: Y...
  MAIL_PASSWORD: OWJjMTVlMW...